[32m2024-04-04 23:24:14 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d47d6e89-d8d1-4b70-9da3-823cb87c1c0b - 27663 - LOGS_CAPTURED - Started capturing logs in process (pid: 27663).
[32m2024-04-04 23:24:14 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d47d6e89-d8d1-4b70-9da3-823cb87c1c0b - 27663 - splitByVIP - STEP_START - Started execution of step "splitByVIP".
[32m2024-04-04 23:24:14 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - d47d6e89-d8d1-4b70-9da3-823cb87c1c0b - 27663 - splitByVIP - STEP_FAILURE - Execution of step "splitByVIP" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "splitByVIP"::

ValueError: Cannot mask with non-boolean array containing NA / NaN values

Stack Trace:
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/Desktop/317_Project_1/314Project1DAG/314Project1DAG/assets.py", line 48, in splitByVIP
    vip = data[data['VIP']]
          ~~~~^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/pandas/core/frame.py", line 4080, in __getitem__
    if com.is_bool_indexer(key):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/pandas/core/common.py", line 136, in is_bool_indexer
    raise ValueError(na_msg)
[0m
