[32m2024-04-04 18:43:41 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d2f9bf4c-51fc-4526-b3f2-37ff6c4c6b16 - 23986 - LOGS_CAPTURED - Started capturing logs in process (pid: 23986).
[32m2024-04-04 18:43:41 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d2f9bf4c-51fc-4526-b3f2-37ff6c4c6b16 - 23986 - training_data - STEP_START - Started execution of step "training_data".
[32m2024-04-04 18:43:41 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - d2f9bf4c-51fc-4526-b3f2-37ff6c4c6b16 - 23986 - training_data - STEP_FAILURE - Execution of step "training_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "training_data"::

FileNotFoundError: [Errno 2] No such file or directory: 'spaceship-titanic/training'

Stack Trace:
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/Desktop/317_Project_1/314Project1DAG/314Project1DAG/assets.py", line 7, in training_data
    data = pd.read_csv("spaceship-titanic/training")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
[0m
