[32m2024-04-24 16:35:58 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b9737784-592d-49dd-8326-4a9eccb7bbad - 14398 - LOGS_CAPTURED - Started capturing logs in process (pid: 14398).
[32m2024-04-24 16:35:58 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b9737784-592d-49dd-8326-4a9eccb7bbad - 14398 - splitCabin - STEP_START - Started execution of step "splitCabin".
[32m2024-04-24 16:35:58 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - b9737784-592d-49dd-8326-4a9eccb7bbad - 14398 - splitCabin - STEP_FAILURE - Execution of step "splitCabin" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "splitCabin"::

NameError: name 'before_count' is not defined

Stack Trace:
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/Desktop/317_Project_1/src/assets.py", line 47, in splitCabin
    counts = [before_count, after_count]
              ^^^^^^^^^^^^
[0m
